name: CI-8.1

on: [push]

env:
  ACTION_PHP_VERSION: 8.1
  ACTION_PHP_EXTENSIONS: zip

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer install
        uses: php-actions/composer@v6
        with:
          php_version: 8.1
          php_extensions: zip gd

      - name: PHPUnit
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          php_version: 8.1
          configuration: phpunit.xml.dist
          php_extensions: zip gd
          test_suffix: Test.php

      - name: PHPStan
        uses: php-actions/phpstan@v3
        with:
          php_version: 8.1
          path: src/

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.1
          path: src/
          standard: phpcs.xml.dist
